/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchoonmaakRouteImport } from './routes/schoonmaak'
import { Route as PrivacybeleidRouteImport } from './routes/privacybeleid'
import { Route as LinkmeRouteImport } from './routes/linkme'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BuitenonderhoudRouteImport } from './routes/buitenonderhoud'
import { Route as AlgemeenBeleidRouteImport } from './routes/algemeen-beleid'
import { Route as IndexRouteImport } from './routes/index'

const SchoonmaakRoute = SchoonmaakRouteImport.update({
  id: '/schoonmaak',
  path: '/schoonmaak',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacybeleidRoute = PrivacybeleidRouteImport.update({
  id: '/privacybeleid',
  path: '/privacybeleid',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkmeRoute = LinkmeRouteImport.update({
  id: '/linkme',
  path: '/linkme',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BuitenonderhoudRoute = BuitenonderhoudRouteImport.update({
  id: '/buitenonderhoud',
  path: '/buitenonderhoud',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgemeenBeleidRoute = AlgemeenBeleidRouteImport.update({
  id: '/algemeen-beleid',
  path: '/algemeen-beleid',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/algemeen-beleid': typeof AlgemeenBeleidRoute
  '/buitenonderhoud': typeof BuitenonderhoudRoute
  '/contact': typeof ContactRoute
  '/impressum': typeof ImpressumRoute
  '/linkme': typeof LinkmeRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/schoonmaak': typeof SchoonmaakRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/algemeen-beleid': typeof AlgemeenBeleidRoute
  '/buitenonderhoud': typeof BuitenonderhoudRoute
  '/contact': typeof ContactRoute
  '/impressum': typeof ImpressumRoute
  '/linkme': typeof LinkmeRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/schoonmaak': typeof SchoonmaakRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/algemeen-beleid': typeof AlgemeenBeleidRoute
  '/buitenonderhoud': typeof BuitenonderhoudRoute
  '/contact': typeof ContactRoute
  '/impressum': typeof ImpressumRoute
  '/linkme': typeof LinkmeRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/schoonmaak': typeof SchoonmaakRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/algemeen-beleid'
    | '/buitenonderhoud'
    | '/contact'
    | '/impressum'
    | '/linkme'
    | '/privacybeleid'
    | '/schoonmaak'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/algemeen-beleid'
    | '/buitenonderhoud'
    | '/contact'
    | '/impressum'
    | '/linkme'
    | '/privacybeleid'
    | '/schoonmaak'
  id:
    | '__root__'
    | '/'
    | '/algemeen-beleid'
    | '/buitenonderhoud'
    | '/contact'
    | '/impressum'
    | '/linkme'
    | '/privacybeleid'
    | '/schoonmaak'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlgemeenBeleidRoute: typeof AlgemeenBeleidRoute
  BuitenonderhoudRoute: typeof BuitenonderhoudRoute
  ContactRoute: typeof ContactRoute
  ImpressumRoute: typeof ImpressumRoute
  LinkmeRoute: typeof LinkmeRoute
  PrivacybeleidRoute: typeof PrivacybeleidRoute
  SchoonmaakRoute: typeof SchoonmaakRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schoonmaak': {
      id: '/schoonmaak'
      path: '/schoonmaak'
      fullPath: '/schoonmaak'
      preLoaderRoute: typeof SchoonmaakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacybeleid': {
      id: '/privacybeleid'
      path: '/privacybeleid'
      fullPath: '/privacybeleid'
      preLoaderRoute: typeof PrivacybeleidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkme': {
      id: '/linkme'
      path: '/linkme'
      fullPath: '/linkme'
      preLoaderRoute: typeof LinkmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buitenonderhoud': {
      id: '/buitenonderhoud'
      path: '/buitenonderhoud'
      fullPath: '/buitenonderhoud'
      preLoaderRoute: typeof BuitenonderhoudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algemeen-beleid': {
      id: '/algemeen-beleid'
      path: '/algemeen-beleid'
      fullPath: '/algemeen-beleid'
      preLoaderRoute: typeof AlgemeenBeleidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlgemeenBeleidRoute: AlgemeenBeleidRoute,
  BuitenonderhoudRoute: BuitenonderhoudRoute,
  ContactRoute: ContactRoute,
  ImpressumRoute: ImpressumRoute,
  LinkmeRoute: LinkmeRoute,
  PrivacybeleidRoute: PrivacybeleidRoute,
  SchoonmaakRoute: SchoonmaakRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
