/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchoonmaakRouteImport } from './routes/schoonmaak'
import { Route as LinkmeRouteImport } from './routes/linkme'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BuitenonderhoudRouteImport } from './routes/buitenonderhoud'
import { Route as IndexRouteImport } from './routes/index'

const SchoonmaakRoute = SchoonmaakRouteImport.update({
  id: '/schoonmaak',
  path: '/schoonmaak',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkmeRoute = LinkmeRouteImport.update({
  id: '/linkme',
  path: '/linkme',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BuitenonderhoudRoute = BuitenonderhoudRouteImport.update({
  id: '/buitenonderhoud',
  path: '/buitenonderhoud',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buitenonderhoud': typeof BuitenonderhoudRoute
  '/contact': typeof ContactRoute
  '/linkme': typeof LinkmeRoute
  '/schoonmaak': typeof SchoonmaakRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buitenonderhoud': typeof BuitenonderhoudRoute
  '/contact': typeof ContactRoute
  '/linkme': typeof LinkmeRoute
  '/schoonmaak': typeof SchoonmaakRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buitenonderhoud': typeof BuitenonderhoudRoute
  '/contact': typeof ContactRoute
  '/linkme': typeof LinkmeRoute
  '/schoonmaak': typeof SchoonmaakRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/buitenonderhoud' | '/contact' | '/linkme' | '/schoonmaak'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/buitenonderhoud' | '/contact' | '/linkme' | '/schoonmaak'
  id:
    | '__root__'
    | '/'
    | '/buitenonderhoud'
    | '/contact'
    | '/linkme'
    | '/schoonmaak'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuitenonderhoudRoute: typeof BuitenonderhoudRoute
  ContactRoute: typeof ContactRoute
  LinkmeRoute: typeof LinkmeRoute
  SchoonmaakRoute: typeof SchoonmaakRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schoonmaak': {
      id: '/schoonmaak'
      path: '/schoonmaak'
      fullPath: '/schoonmaak'
      preLoaderRoute: typeof SchoonmaakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkme': {
      id: '/linkme'
      path: '/linkme'
      fullPath: '/linkme'
      preLoaderRoute: typeof LinkmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buitenonderhoud': {
      id: '/buitenonderhoud'
      path: '/buitenonderhoud'
      fullPath: '/buitenonderhoud'
      preLoaderRoute: typeof BuitenonderhoudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuitenonderhoudRoute: BuitenonderhoudRoute,
  ContactRoute: ContactRoute,
  LinkmeRoute: LinkmeRoute,
  SchoonmaakRoute: SchoonmaakRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
